=== MartDiVenus/XMLUX/documentClasses/data/data-seven/esempi/marginTrue/prova.dtd
<!-- Root = a= titulus = title = radix = radix a -->
<!ELEMENT radix ANY>
<!-- All that is in "gradusI" = gradusI = a01 -->
<!ELEMENT gradusI (#PCDATA)>
<!ATTLIST gradusI ID CDATA "a01">
<!-- All that is in "gradusI" = gradusI = a02 -->
<!ELEMENT gradusI (#PCDATA)>
<!ATTLIST gradusI ID CDATA "a02">
<!-- All that is under "gradusII" = gradusII = a01.01 -->
<!ELEMENT gradusII (gradusIII+, gradusIV+, gradusV+, gradusVI+, gradusVII+)>
<!ATTLIST gradusII ID CDATA "a01.01">
<!-- All that is under "gradusII" = gradusII = a02.01 -->
<!ELEMENT gradusII (gradusIII+, gradusIV+, gradusV+, gradusVI+, gradusVII+)>
<!ATTLIST gradusII ID CDATA "a02.01">
<!-- All that is under "gradusIII" = gradusIII = a01.01.01 -->
<!ELEMENT gradusIII (gradusIV+, gradusV+, gradusVI+, gradusVII+)>
<!ATTLIST gradusIII ID CDATA "a01.01.01">
<!-- All that is under "gradusIII" = gradusIII = a01.01.02 -->
<!ELEMENT gradusIII (gradusIV+, gradusV+, gradusVI+, gradusVII+)>
<!ATTLIST gradusIII ID CDATA "a01.01.02">
<!-- All that is under "gradusIII" = gradusIII = a02.01.01 -->
<!ELEMENT gradusIII (gradusIV+, gradusV+, gradusVI+, gradusVII+)>
<!ATTLIST gradusIII ID CDATA "a02.01.01">
<!-- All that is under "gradusIV" = gradusIV = a01.01.01.01 -->
<!ELEMENT gradusIV (gradusV+, gradusVI+, gradusVII+)>
<!ATTLIST gradusIV ID CDATA "a01.01.01.01">
<!-- All that is under "gradusIV" = gradusIV = a01.01.02.01 -->
<!ELEMENT gradusIV (gradusV+, gradusVI+, gradusVII+)>
<!ATTLIST gradusIV ID CDATA "a01.01.02.01">
<!-- All that is under "gradusIV" = gradusIV = a02.01.01.01 -->
<!ELEMENT gradusIV (gradusV+, gradusVI+, gradusVII+)>
<!ATTLIST gradusIV ID CDATA "a02.01.01.01">
<!-- All that is under "gradusV" = gradusV = a01.01.01.01.01 -->
<!ELEMENT gradusV (gradusVI+, gradusVII+)>
<!ATTLIST gradusV ID CDATA "a01.01.01.01.01">
<!-- All that is under "gradusV" = gradusV = a01.01.02.01.01 -->
<!ELEMENT gradusV (gradusVI+, gradusVII+)>
<!ATTLIST gradusV ID CDATA "a01.01.02.01.01">
<!-- All that is under "gradusV" = gradusV = a02.01.01.01.01 -->
<!ELEMENT gradusV (gradusVI+, gradusVII+)>
<!ATTLIST gradusV ID CDATA "a02.01.01.01.01">
<!-- All that is under "gradusVI" = gradusVI = a01.01.01.01.01.01 -->
<!ELEMENT gradusVI (gradusVII+)>
<!ATTLIST gradusVI ID CDATA "a01.01.01.01.01.01">
<!-- All that is under "gradusVI" = gradusVI = a01.01.02.01.01.01 -->
<!ELEMENT gradusVI (gradusVII+)>
<!ATTLIST gradusVI ID CDATA "a01.01.02.01.01.01">
<!-- All that is under "gradusVI" = gradusVI = a02.01.01.01.01.01 -->
<!ELEMENT gradusVI (gradusVII+)>
<!ATTLIST gradusVI ID CDATA "a02.01.01.01.01.01">
<!-- All that is in "gradusVII" = gradusVII = a01.01.01.01.01.01.01 -->
<!ELEMENT gradusVII (#PCDATA)>
<!ATTLIST gradusVII ID CDATA "a01.01.01.01.01.01.01">
<!-- All that is in "gradusVII" = gradusVII = a01.01.02.01.01.01.01 -->
<!ELEMENT gradusVII (#PCDATA)>
<!ATTLIST gradusVII ID CDATA "a01.01.02.01.01.01.01">
<!-- All that is in "gradusVII" = gradusVII = a02.01.01.01.01.01.01 -->
<!ELEMENT gradusVII (#PCDATA)>
<!ATTLIST gradusVII ID CDATA "a02.01.01.01.01.01.01">
 
<!-- Constants -->

=== MartDiVenus/XMLUX/documentClasses/data/data-seven/esempi/prova.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="prova.css"?>
<!DOCTYPE a SYSTEM "prova.dtd">
<!-- septem gradus data document class -->

<!-- begin radix -->
<radix ID="a" name="a">Title

<gradusI ID="a01" name="gradusI">GradusI a01

<gradusII ID="a01.01" name="gradusII">GradusII a01.01

<gradusIII ID="a01.01.01" name="gradusIII">GradusIII a01.01.01

<gradusIV ID="a01.01.01.01" name="gradusIV">GradusIV a01.01.01.01

<gradusV ID="a01.01.01.01.01" name="gradusV">GradusV a01.01.01.01.01

<gradusVI ID="a01.01.01.01.01.01" name="gradusVI">GradusVI a01.01.01.01.01.01

<gradusVII ID="a01.01.01.01.01.01.01" name="gradusVII">GradusVII a01.01.01.01.01.01.01

</gradusVII>
<!-- end a01.01.01.01.01.01.01 -->

</gradusVI>
<!-- end a01.01.01.01.01.01 -->

</gradusV>
<!-- end a01.01.01.01.01 -->

</gradusIV>
<!-- end a01.01.01.01 -->

</gradusIII>
<!-- end a01.01.01 -->

<gradusIII ID="a01.01.02" name="gradusIII">GradusIII a01.01.02

<gradusIV ID="a01.01.02.01" name="gradusIV">GradusIV a01.01.02.01

<gradusV ID="a01.01.02.01.01" name="gradusV">GradusV a01.01.02.01.01

<gradusVI ID="a01.01.02.01.01.01" name="gradusVI">GradusVI a01.01.02.01.01.01

<gradusVII ID="a01.01.02.01.01.01.01" name="gradusVII">GradusVII a01.01.02.01.01.01.01

</gradusVII>
<!-- end a01.01.02.01.01.01.01 -->

</gradusVI>
<!-- end a01.01.02.01.01.01 -->

</gradusV>
<!-- end a01.01.02.01.01 -->

</gradusIV>
<!-- end a01.01.02.01 -->

</gradusIII>
<!-- end a01.01.02 -->
</gradusII>
<!-- end a01.01 -->

</gradusI>
<!-- end a01 -->

<gradusI ID="a02">GradusI a02

<gradusII ID="a02.01" name="gradusII">GradusII a02.01

<gradusIII ID="a02.01.01" name="gradusIII">GradusIII a02.01.01

<gradusIV ID="a02.01.01.01" name="gradusIV">GradusIV a02.01.01.01

<gradusV ID="a02.01.01.01.01" name="gradusV">GradusV a02.01.01.01.01

<gradusVI ID="a02.01.01.01.01.01" name="gradusVI">GradusVI a02.01.01.01.01.01

<gradusVII ID="a02.01.01.01.01.01.01" name="gradusVII">GradusVII a02.01.01.01.01.01.01

</gradusVII>
<!-- end a02.01.01.01.01.01.01 -->

</gradusVI>
<!-- end a02.01.01.01.01.01 -->

</gradusV>
<!-- end a02.01.01.01.01 -->

</gradusIV>
<!-- end a02.01.01.01 -->

</gradusIII>
<!-- end a02.01.01 -->

</gradusII>
<!-- end a02.01 -->

</gradusI>
<!-- end a02 -->

</radix>
