=== MartDiVenus/XMLUX/documentClasses/data/categoryDataset/esempi/categoryDataset02/marginTrue/prova.dtd
<!-- Root = a= titulus = title = category dataset 01  = CategoryDataset a -->
<!ELEMENT CategoryDataset ANY>
<!-- All that is under "Series" = Series = a01 -->
<!ELEMENT Series (Item+, Key+, Value+)>
<!ATTLIST Series ID CDATA "a01">
<!-- All that is under "Series" = Series = a02 -->
<!ELEMENT Series (Item+, Key+, Value+)>
<!ATTLIST Series ID CDATA "a02">
<!-- All that is under "Item" = Item = a01.01 -->
<!ELEMENT Item (Key+, Value+)>
<!ATTLIST Item ID CDATA "a01.01">
<!-- All that is under "Item" = Item = a01.02 -->
<!ELEMENT Item (Key+, Value+)>
<!ATTLIST Item ID CDATA "a01.02">
<!-- All that is under "Item" = Item = a01.03 -->
<!ELEMENT Item (Key+, Value+)>
<!ATTLIST Item ID CDATA "a01.03">
<!-- All that is under "Item" = Item = a02.01 -->
<!ELEMENT Item (Key+, Value+)>
<!ATTLIST Item ID CDATA "a02.01">
<!-- All that is under "Item" = Item = a02.02 -->
<!ELEMENT Item (Key+, Value+)>
<!ATTLIST Item ID CDATA "a02.02">
<!-- All that is under "Item" = Item = a02.03 -->
<!ELEMENT Item (Key+, Value+)>
<!ATTLIST Item ID CDATA "a02.03">
<!-- All that is in "Key or Value" = Key = a01.01.01 -->
<!ELEMENT Key (#PCDATA)>
<!ATTLIST Key ID CDATA "a01.01.01">
<!-- All that is in "Key or Value" = Value = a01.01.02 -->
<!ELEMENT Value (#PCDATA)>
<!ATTLIST Value ID CDATA "a01.01.02">
<!-- All that is in "Key or Value" = Key = a01.02.01 -->
<!ELEMENT Key (#PCDATA)>
<!ATTLIST Key ID CDATA "a01.02.01">
<!-- All that is in "Key or Value" = Value = a01.02.02 -->
<!ELEMENT Value (#PCDATA)>
<!ATTLIST Value ID CDATA "a01.02.02">
<!-- All that is in "Key or Value" = Key = a01.03.01 -->
<!ELEMENT Key (#PCDATA)>
<!ATTLIST Key ID CDATA "a01.03.01">
<!-- All that is in "Key or Value" = Value = a01.03.02 -->
<!ELEMENT Value (#PCDATA)>
<!ATTLIST Value ID CDATA "a01.03.02">
<!-- All that is in "Key or Value" = Key = a02.01.01 -->
<!ELEMENT Key (#PCDATA)>
<!ATTLIST Key ID CDATA "a02.01.01">
<!-- All that is under "Key or Value" = Value = a02.01.02 -->
<!ELEMENT Value (Item+, Key+, Value+)>
<!ATTLIST Value ID CDATA "a02.01.02">
<!-- All that is in "Key or Value" = Key = a02.02.01 -->
<!ELEMENT Key (#PCDATA)>
<!ATTLIST Key ID CDATA "a02.02.01">
<!-- All that is in "Key or Value" = Value = a02.02.02 -->
<!ELEMENT Value (#PCDATA)>
<!ATTLIST Value ID CDATA "a02.02.02">
<!-- All that is in "Key or Value" = Key = a02.03.01 -->
<!ELEMENT Key (#PCDATA)>
<!ATTLIST Key ID CDATA "a02.03.01">
<!-- All that is in "Key or Value" = Value = a02.03.02 -->
<!ELEMENT Value (#PCDATA)>
<!ATTLIST Value ID CDATA "a02.03.02">
 
<!-- Constants -->

=== MartDiVenus/XMLUX/documentClasses/data/categoryDataset/esempi/categoryDataset01/marginTrue/prova.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="prova.css"?>
<!DOCTYPE a SYSTEM "prova.dtd">
<!-- category dataset 01 document class -->

<!-- begin radix -->
<CategoryDataset ID="a" name="a">Passioni
	<Series ID="a01" name = "Discipline">Series n. 1
    		<Item ID="a01.01" name = "Item a01.01">Item n. 1
    			<Key ID="a01.01.01" name = "Key a01.01.01">Musica</Key>
    			<!-- end a01.01.01 -->
    			<Value ID="a01.01.02" name = "Value a01.01.02">100.4</Value>
			<!-- end a01.01.02 -->
    		</Item>
		<!-- end a01.01 --> 
		<Item ID="a01.02" name = "Item a01.02">Item n. 2
			<Key ID="a01.02.01" name = "Key a01.02.01">Pittura</Key>
			<!-- end a01.02.01 -->
      			<Value ID="a01.02.02" name = "Value a01.02.02">75.5</Value>
			<!-- end a01.02.02 -->
		</Item>
		<!-- end a01.02 --> 
	</Series>
</CategoryDataset>
